### ISSUE TITLE
List of life stages/behaviours/associations for each species/species group

### ISSUE THREAD

**Issue by MikeLush** [jncc/vsas-app-development#45] opened 2023-11-17 10:32 UTC
Need from Emma.

**Comment by Emmawilsonjncc** [comment] 2023-11-29 09:56
Provided on other comment but attached again here for ease

[New form layout_FOR IDOX.xlsx](https://github.com/jncc/vsas-app-development/files/13498916/New.form.layout_FOR.IDOX.xlsx)

**Comment by ClaireLush** [comment] 2023-11-29 12:23
Duplicate of #50

**Closed by ClaireLush** 2023-11-29 12:23 UTC
